### ISSUE TITLE
add python code in linear equations document on algebra & measure concentration and dispersion on statistic

### ISSUE THREAD

**Issue by rrayhka** [xirf/mathwithcode#10]
dude i wanna contrib in linear equations and statistic, especially in python code.

**Comment by xirf** [comment]
We're glad you want to contribute, and even more so you want to work in the linear equations and statistics sections. But of course we’re always excited to have new contributors.

Don’t forget to follow our contributor guidelines here and save a add to yourself in [contributors list](https://github.com/xirf/mathwithcode/blob/master/docs/.vitepress/contributors.ts) to show you at homepage

**Comment by rrayhka** [comment]
thanks mate for the opportunity, i appreciate that

**Comment by xirf** [comment]
closed with #13 #14
