### ISSUE TITLE
Add "Calculus" section and a sub section talk about limit.

### ISSUE THREAD

**Issue by windofbay** [xirf/mathwithcode#26]
Explanation about concept of limit of a function in math.

**Comment by xirf** [comment]
That would be nice to have, i count on you. (⁠≧⁠▽⁠≦⁠)

**Comment by windofbay** [comment]
Kak saya ingin commit kode saya ke sini. Tapi masih belum bisa karena tidak ada izin/akses. Bagaimana? makasih

**Comment by xirf** [comment]
Untuk tutorialnya, kamu bisa mengikuti langkah-langkah berikut:

1. Klik tombol "Fork" yang ada di dekat tombol bintang untuk membuat salinan dari repository ini ke akunmu.

2. Setelah repository berhasil di-fork, buka terminal di kode kamu dan jalankan perintah berikut untuk menambahkan fork sebagai remote:
   ```bash
   git remote add origin-fork https://github.com/usernamekamu/repokamu
   ```

3. Setelah melakukan perubahan, tambahkan, commit, dan push dengan perintah berikut:
   ```bash
   git add .
   git commit -m "Pesan commit"
   git push -u origin-fork main
   ```

4. Kunjungi `https://github.com/usernamekamu/repokamu`. Nanti akan ada tombol hijau bertuliskan "Pull Request". Klik tombol tersebut untuk membuat pull request ke repository asli.


Kalo masih bingung ini ad tutorial yang bakalan bantu:

https://github.com/bantenprov/cara-penggunaan-github?tab=readme-ov-file#untuk-non-kontributor

**Comment by windofbay** [comment]
Oke siap kak, + saya ingin tanya beberapa terkait kodingan di Inbox facebook kak Tama, boleh tolong diperiksa, ya.

**Comment by xirf** [comment]
Okei kak boleh kok

**Comment by rrayhka** [comment]
@wchynto lessgo

**Comment by rrayhka** [comment]
> That would be nice to have, i count on you. (⁠≧⁠▽⁠≦⁠)

i think this repo must be add new branch for calculus, it would be easier to develop

**Comment by xirf** [comment]
> > That would be nice to have, i count on you. (⁠≧⁠▽⁠≦⁠)
> 
> i think this repo must be add new branch for calculus, it would be easier to develop

Don't hesitate to add your own new branches, just don't push straight to master branch.

I also have plans to move this repo to @mathwithcode organization so everyone can contribute and maintain easily

**Comment by rrayhka** [comment]
> > > That would be nice to have, i count on you. (⁠≧⁠▽⁠≦⁠)
> > 
> > 
> > i think this repo must be add new branch for calculus, it would be easier to develop
> 
> Don't hesitate to add your own new branches, just don't push straight to master branch.
> 
> I also have plans to move this repo to @mathwithcode organization so everyone can contribute and maintain easily

ah yeah, i forgot that i can make new branch on my fork, haha
