### ISSUE TITLE
Add Simple Linear Regression on Statistic sub section

### ISSUE THREAD

**Issue by fadjarrafi** [xirf/mathwithcode#28]
Halo kak, pernisi aku mau ijin ikut contrib nambahin materi regresi linear sederhana di subbab statistik

**Comment by xirf** [comment]
halo ak terimakasih atas bantuannya untuk tambah materi. Akan kami tunggu pull requestnya. semangat ya kak!!!

**Comment by xirf** [comment]
Closed on #34
