### ISSUE TITLE
Pengangkatan Artikel

### ISSUE THREAD

**Issue by hawariMuflihMunte** [xirf/mathwithcode#35]
Saya sangat senang dengan adanya proyek ini, karena memungkinkan para programmer untuk belajar matematika sekaligus memahami cara menulis kode secara logis. Oleh karena itu, saya ingin meminta izin untuk mengangkat terobosan terbaru ini ke dalam artikel saya atas izin pemilik/pemegang kepentingan.

Saya berharap dapat segera menerima jawaban dari project lead, sehingga inovasi ini dapat disebarluaskan ke khalayak umum dan menjangkau lebih banyak orang.

Link draft penulisan, https://medium.com/@hawari.muflih.munte/learning-math-with-code-34aee5d8d7de

**Comment by xirf** [comment]
Halo terimakasih atas inisiatifnya, untuk artikel dari saya sendiri memperbolehkan.
Sebagai tambahan saat ini sudah ada bahasa indonesia dan bahasa inggris meskipun belum semua materi diterjemahkan.

**Comment by xirf** [comment]
Also you probably want to mail us at contact@mathwithcode.tech

**Comment by hawariMuflihMunte** [comment]
> Halo terimakasih atas inisiatifnya, untuk artikel dari saya sendiri memperbolehkan. Sebagai tambahan saat ini sudah ada bahasa indonesia dan bahasa inggris meskipun belum semua materi diterjemahkan.

Maaf, saya tadi belum mengecek secara keseluruhan dari halaman web nya. Dan ternyata sebagian besar materi telah tersedia dalam bahasa Inggris.

**Comment by xirf** [comment]
Good luck, and thanks for you article, Hopefully you can give some contibution to lessons too :innocent:
