### ISSUE TITLE
Add Quartile, Decile, and Percentile on Percent Sub Section

### ISSUE THREAD

**Issue by ninoslat1** [xirf/mathwithcode#5]
Permisi kak, boleh ijin contribute operasi kuartil, desil, dan persentil di subbab Persen?

**Comment by xirf** [comment]
Halo kak boleh banget kak silahkan buka pull request ya nanti aku tinjau :3 
Semangat kak!!!

**Comment by ninoslat1** [comment]
Oke makasih kak

**Comment by xirf** [comment]
close with #6
